# Generated by Django 6.1 on 2026-08-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_no',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='products.product'),
        ),
    ]
