# Generated by Django 6.1 on 2026-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='source_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('EXPENSE', 'Expense'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
