# Generated by Django 6.1 on 2026-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_alter_cashbookentry_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='source_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('EXPENSE', 'Expense'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
